### PR TITLE
Error parsing URL to play

### PR DESCRIPTION
**Pull request by gdachs**
I get an error if I want to cast movies to plexbmc:

```
2:09:12 T:140411876144896  NOTICE: PleXBMC -> Mode: 5
22:09:12 T:140411876144896  NOTICE: PleXBMC -> URL: https://192-168-99-10.<hash replaced>.plex.direct:32400/library/metadata/21407
22:09:12 T:140411876144896  NOTICE: PleXBMC -> Name:
22:09:12 T:140411876144896  NOTICE: PleXBMC -> identifier: None
22:09:12 T:140411876144896  NOTICE: PleXBMC.plex -> get_server_from_ip : IP to lookup: 192-168-99-10.<hash replaced>.plex.direct:32400
22:09:12 T:140411876144896  NOTICE: PleXBMC.plex -> get_server_from_ip : Not an IP Address
22:09:12 T:140411876144896  NOTICE: PleXBMC -> getXML : == ENTER ==
22:09:12 T:140411876144896  NOTICE: PleXBMC.plex -> get_server_from_ip : IP to lookup: 192-168-99-10.<hash replaced>.plex.direct:32400
22:09:12 T:140411876144896  NOTICE: PleXBMC.plex -> get_server_from_ip : Not an IP Address
22:09:12 T:140411876144896  NOTICE: PleXBMC.plexserver -> processed_xml : We have been passed a full URL. Parsing out path
22:09:12 T:140411876144896  NOTICE: PleXBMC.plexserver -> talk : URL is: /library/metadata/21407
22:09:12 T:140411876144896  NOTICE: PleXBMC.plexserver -> talk : Server: 127.0.0.1 is offline or uncontactable. error: ('Connection aborted.', error(111, 'Connection refused'))
22:09:12 T:140411876144896  NOTICE: PleXBMC.plexserver -> processed_xml : PARSE: it took 0.00 seconds to parse data from 127.0.0.1
22:09:12 T:140411876144896  NOTICE: PleXBMC -> getAudioSubtitlesMedia : == ENTER ==
22:09:12 T:140411876144896  NOTICE: PleXBMC -> getAudioSubtitlesMedia : Gather media stream info
22:09:12 T:140411876144896  NOTICE: PleXBMC -> getAudioSubtitlesMedia : No Video data found
22:09:12 T:140411876144896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('type',)
                                            Traceback (most recent call last):
                                              File "/home/gda/.kodi/addons/plugin.video.plexbmc-helix/default.py", line 13, in <module>
                                                plexbmc.start_plexbmc()
                                              File "/home/gda/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plexbmc.py", line 4213, in start_plexbmc
                                                playLibraryMedia(param_url,force=force, override=play_transcode)
                                              File "/home/gda/.kodi/addons/plugin.video.plexbmc-helix/resources/lib/plexbmc.py", line 1117, in playLibraryMedia
                                                if force and streams['type'] == "music":
                                            KeyError: ('type',)
                                            -->End of Python script error report<--
```

The fallback server 127.0.0.1 doesn't help because my clients don't host a server.

In this pull request I have an ugly workaround that helps me. Maybe you get a better idea when you see it.

### CODE REVIEW

**Comment by BigYesh** [comment]
Any chance of this getting merged, as I'm encountering the same problem. My current setup is getting urls of the form:  https://192-168-1-4.2fe780b9456b4d50a18f13ab5bc38208.plex.direct:32400/library/metadata/168696 when I try to cast from web app to Kodi. This obviously fails the current tests in the code, and so it falls back to 127.0.0.1, which doesn't work. 

Let me know if there's anything I can do to help this get in, as I'm eager to see PlexBMC cope with this.

**Comment by janecker** [comment]
This commit fixed problems I had when try to playback media using the Android app. Would be perfect if this could be merged.

**Comment by hippojay** [comment]
I've just merged a change for DNS lookups, which should also fix this.  If not I'll look further.

**Comment by gdachs** [comment]
No, doesn't help:

```
7:21 T:2594247744  NOTICE: PleXBMC -> Detected parameters: {'url': 'https://192-168-99-10.1aeabc50fb9b41aea0d4bcd63bcee478.plex.direct:32400/library/metadata/36311', 'force': '2861000', 'mode': '5'}             
7:42 T:2594247744  NOTICE: PleXBMC.plexserver -> talk : Server: 127.X.X.1 is offline or uncontactable. error: HTTPSConnectionPool(host='127.X.X.1', port=32400): Max retries exceeded with url: /library/metadata/3
7:42 T:2594247744   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--                                                                                     
                                         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                                                                                           
                                        Error Type: <type 'exceptions.KeyError'>                                                                                                                                   
                                        Error Contents: ('type',)                                                                                                                                                  
                                        Traceback (most recent call last):                                                                                                                                         
                                          File "/storage/.kodi/addons/plugin.video.plexbmc-Isengard/default.py", line 12, in <module>                                                                              
                                            plexbmc.start_plexbmc()                                                                                                                                                
                                          File "/storage/.kodi/addons/plugin.video.plexbmc-Isengard/resources/lib/plexbmc.py", line 4362, in start_plexbmc                                                         
                                            play_library_media(param_url, force=force, override=play_transcode)                                                                                                    
                                          File "/storage/.kodi/addons/plugin.video.plexbmc-Isengard/resources/lib/plexbmc.py", line 1146, in play_library_media                                                    
                                            if force and streams['type'] == "music":                                                                                                                               
                                        KeyError: ('type',)                                                                                                                                                        
                                        -->End of Python script error report<--
```

NS Lookup is not the problem, it is allready a Name, it looks only like an IP.

Gerald

**Comment by BigYesh** [comment]
So close. With the latest plugin we get a slightly different error:

```
20:48:57 T:139803826693888  NOTICE: PleXBMC.plex -> get_server_from_ip : IP to lookup: 192-168-1-4.2fe780b9456b4d50a18f13ab5bc38208.plex.direct:32400
20:48:57 T:139803826693888  NOTICE: PleXBMC.plex -> get_server_from_ip : [jayesh-storage] - checking ip:192-168-1-4.2fe780b9456b4d50a18f13ab5bc38208.plex.direct against server ip 192.168.1.4
20:48:57 T:139803826693888  NOTICE: PleXBMC.plexserver -> find_address_match : Checking [192-168-1-4.2fe780b9456b4d50a18f13ab5bc38208.plex.direct:32400] against [192.168.1.4:32400]
20:48:57 T:139803826693888  NOTICE: PleXBMC.plexserver -> find_address_match : Checking [192-168-1-4.2fe780b9456b4d50a18f13ab5bc38208.plex.direct:32400] against [None]
20:48:57 T:139803826693888  NOTICE: PleXBMC.plexserver -> find_address_match : Checking [192-168-1-4.2fe780b9456b4d50a18f13ab5bc38208.plex.direct:32400] against [192-168-1-4.2fe780b9456b4d50a18f13ab5bc38208.plex.direct:32400]
20:48:57 T:139803826693888  NOTICE: PleXBMC.plex -> get_server_from_ip : Unable to translate - Returning new plexserver set to 192-168-1-4.2fe780b9456b4d50a18f13ab5bc38208.plex.direct
20:48:57 T:139803826693888   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
```

This seemed very confusing as it looks like the find_address_match function should have returned true. However it turns out there is a typo in plexserver.py, line 170:

`log_print.debug("Checking [%s:%s] against [%s:%s]" % ( ipaddress, port, ipaddress, 32400 ))`

should say:

`log_print.debug("Checking [%s:%s] against [%s:%s]" % ( ipaddress, port, test_address, 32400 ))`

It still fails because it is trying to compare the hostname against the ipaddress of the server. This can be fixed by changing line 534 in plex.py from:

```
            try:
                import socket
                socket.gethostbyname(ip)
```

to:

```
            try:
                import socket
                ip = socket.gethostbyname(ip)
```

That seems to resolve the issue for me, as I am then able to cast files to my copy of Kodi. 

Let me know if you need me to raise a PR or do anything else!

**Comment by gdachs** [comment]
I have found another error some lines before.

```
21:23:31 T:2675127360   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urlli
                                              InsecurePlatformWarning                                                                                                                                              
21:23:31 T:2795500608   DEBUG: webserver: request received for /jsonrpc                                                                                                                                            
21:23:31 T:2675127360  NOTICE: HTTP response error: 422
```

I use OpenELEC 6.0 on a Wetek Play. It has Python 2.7.3. This bug should be fixed with 2.7.9. I build currently the master branch that has 2.7.10. Will test after this.

**Comment by gdachs** [comment]
@BigYesh: I still don't get your error message, I have used the isengard branch. What version of the addon did you use?

**Comment by BigYesh** [comment]
I'm just using the latest git code from isengard-fixes. I've turned on debugging in pleXBMC helper and in the main addon itself and picked the most verbose level for each.

**Comment by devshans** [comment]
@gdachs I can confirm seeing the same issues with the IP being parsed on the latest helix branch. I merged in your regex fix and it fixed the problem. 

The IP lookup seems to be working fine, the address just needs to be extracted before passing or in get_server_from_ip. @hippojay Is this part of a larger bug fix or could we look at getting this workaround getting merged?

**Comment by gdachs** [comment]
Works now without this patch on branch isengard-helper-merge.

Gerald

**Pull request closed without merging**
