### PR TITLE
Problems with Kodi 16 fixed

### PR DESCRIPTION
**Pull request by neffs**
This works with Kodi 16 RC1 on FireTV.

Sorting was messed up because the sort methods got different IDs.

declare_namespace error was fixed

mediatype now should be set explicitly

### CODE REVIEW

**Comment by hippojay** [comment]
Thanks - will check it out.  I'll need to test on isengard as well, just to make sure.

**Comment by kodiadmin** [comment]
update

**Comment by kodiadmin** [comment]
fallback_movies
fanart

**Comment by kodiadmin** [comment]
icon

**Comment by kodiadmin** [comment]
[zip.zip](https://github.com/hippojay/plugin.video.plexbmc/files/115549/zip.zip)

**Comment by Remco32** [comment]
Thanks!

**Pull request closed without merging**
