### PR TITLE
ADD: Option to enable subtitles by default

### PR DESCRIPTION
**Pull request by ghost**
Without this option, subtitle users have to enable subtitles in the Audio-Settings menu each time they start a video. Wanted to base the decision on the Languages -> Subtitle mode of the PMS, but cannot find out how to read the setting from the server.

If you have other ideas of how to implement such a function or can give a hint on how to read the setting from the PMS, please let me know. Couldn't find it in the API documentation.

### CODE REVIEW

**Comment by hippojay** [comment]
Should need to do this.

PLexbmc will read the /library/metadata/nnnnnn XML, which will show available audio and subtitle streams.  PMS should already have marked some of these as selected='1', which is does as part of processing the media file.

Plexbmc shoudl then take these sleection and apply them:
xbmc.player().setAudio to set the audio stream
xbmc.player().setSubtitleStream to set and enbedded stream
xbmc.player().setSubtitles to set an external subtitle source.

Originally these are supposed to set and enable, but perhaps the enable part wasn;t implemented (or has been missed out, when XBMC changed they way is created the python code).  So I should do a showSubtitles - however it looks like I may have accidently set these to False, not True.

I'll retest and confirm.

**Comment by hippojay** [comment]
I've just  tested, and I can get subtitiles on or off as dictaed to by PMS, rather than having to force themon or off.  Do you want to check and confirm?

**Comment by ghost** [comment]
Overlooked that. Thanks for elaborating. Will do some testing tomorrow to confirm.

**Comment by ghost** [comment]
Confirmed, the subtitle setting on the PMS is now reflected in PleXBMC.

**Comment by hippojay** [comment]
Great - thanks for reporting, testing and spending the time to look at the code.

**Comment by ghost** [comment]
You're welcome. Thank you for maintaining the add-on and taking it to where it is today.

If you can use my help please tell me what I can do. I'm not that advanced in Python but usually I can handle things pretty self-sufficient.

**Pull request closed without merging**
