### PR TITLE
Refactor/packages

### PR DESCRIPTION
**Pull request by dukobpa3**
Look at this. This is refactored "common" package.
It is just for example because of I think that you should make stable release 4.0. before merge.

### CODE REVIEW

**Comment by hippojay** [comment]
ok - i'll check it out later.  Didn't realise you were going to go all PEP :)  I did have a look at doing this, but  i needed to focus on the functions.  

Also, what branch did you base these changes on?  Again I can see a lot of older commits from a long time ago.  It just makes it more difficult to work out what changes are actually being done.

**Comment by dukobpa3** [comment]
I've merged helix to master and moved base on it in my fork

**Comment by dukobpa3** [comment]
But you can merge to helix. Don't worry ))

**Comment by dukobpa3** [comment]
> i needed to focus on the functions.

Why?

**Comment by hippojay** [comment]
Did you use a PEP enforcement tool?  There is a lot here to do by hand!

Overall thought it looks fine - tidies up my sloppy coding :)

As for why I need to focus on functions - it was when I picked up plexbmc again.  The objective was to get plexhome compatible as there were a lot of reported failures and the code (in pretty much a single file) was a mess.   After that (which is hopefully going to be this v4 shortly) then the pressure is off for basic compatibility and we can look at internal changes, re-architecture and other stuff.

**Comment by dukobpa3** [comment]
> Did you use a PEP enforcement tool?

Just a good IDE
this: https://www.jetbrains.com/idea/
or this: https://www.jetbrains.com/pycharm/

> objective was to get plexhome compatible

what compatible with?))

**Comment by hippojay** [comment]
IDE?  Bahh - I use notepad++  :)   Before this, I used to write scripts with vi - so notepad++ was a big bonus!   I did look at pycharm, but because of the kodi module dependencies it wasn't straight forward.  Happy to be shown otherwise - I'm not a software developer by trade, so any tools that make it quicker/better/consistent would be great.

The compatibility I had to get was to make sure that plexbmc worked correctly with the Plex extra authentication (plexhome).  It was apparent that it wasn't working correctly and needed some major work doing to it to make it work.  This was the priority at the time.

Now this looks to be done - we can look at other stuff now (like this)

**Comment by Rockycjc** [comment]
I keep getting notification emails so I am just gonna jump in. I'd like it
if you could add the ability to utilize th e new plex enhanced music
features....particularly pulling the vevo music videos.

**Comment by dukobpa3** [comment]
Don't need to merge. Just for example.

**Pull request closed without merging**
