### PR TITLE
Up master to latest :) 

### PR DESCRIPTION
**Pull request by dukobpa3**
Subj.
It s able to automerge :)

### CODE REVIEW

**Comment by hippojay** [comment]
Thanks for the two translations.  There is an issue with the pull requests in that they are mixed in with my commits.  I'm not entirely sure what will happen if I try to auto-merge them.   What I will do is extract the two files and manually add them to plexbmc with you stated as the author/contributor.

**Comment by dukobpa3** [comment]
I want just translation)))
I don't need author state ;)

**Comment by dukobpa3** [comment]
But I sure you can automerge it.
Mix with your commits it is just because I've updated my branches to your latest commits.
Look to changes, not to commits.

**Comment by hippojay** [comment]
Thanks - added

**Pull request closed without merging**
