### PR TITLE
ADD: Support for new Plex Timeline API in PMS v0.9.8.x. Also allow support for previous versions

### PR DESCRIPTION
**Pull request by wezhunter**
Allows for Plex/Web status viewing of clients using PleXBMC client.
Also allows for Multi User support of per user Watched Status because the Timeline API implements this feature natively

### CODE REVIEW

**Comment by hippojay** [comment]
Thanks. I'll check this out. I've been really really busy at work which has pushed plexbmc right down the list at the moment.   In fact, so much that I don't think I've even sat down to watch anything on it for a month!

**Comment by wezhunter** [comment]
No worries anytime :-)
Yeah know that feeling, very up and down here too. 
At least your busy with work though, can think of far worse issues ;-) It'll settle down again at some point, I'm sure...

Good luck anyhoo's....

**Comment by wezhunter** [comment]
I've added some more commits. Spent quite a bit of time re-basing a lot of methods I created, much cleaner and faster now too (doesn't call resolveAllServers just for a version check)

Also introduced new HTTPS support for client/server comms. Working perfectly well here. Falls back to HTTP if unable to determine server version or server version isn't 0.9.8.0+

My next step is to test/work out how to remove the X-Plex-Token query string param and move it all to the http header. That way it increases overall transport security somewhat, especially combined with the new HTTPS/SSL support!

**Comment by christianselch** [comment]
Hallo @hippojay 

Will this ever be implanted into the main repo or one of the branches? I'd love to be able to take advantage of the timeline API's features

Best regards

**Comment by Christolito** [comment]
Hats off @hippojay! Would love to see support for now playing on Plexbmc. Any chance on seeing this in a release? Cheers!

**Comment by austin1howard** [comment]
With hippojay not involved in development much anymore, I'm not sure if we'll have time to work on this...

The PR will no longer merge...wezhunter do you know why?

**Comment by wickning1** [comment]
Helper is already submitting this info, which may be enough for most people?  I'm sure there are merge conflicts with this PR, it was branched a long time ago.

**Comment by austin1howard** [comment]
I think let's just keep Helper and PleXBMC separate. It makes development simpler too, I think, since it's already in place.

**Pull request closed without merging**
