### PR TITLE
sometimes server are not discovered on the first try, retry it then

### PR DESCRIPTION
**Pull request by gdachs**
Sometimes the Home Shelf doesn't show up. If this happens, then the discover() function returns an empty server_list. This ugly workaround seems to work reliable.

### CODE REVIEW

**Comment by hippojay** [comment]
Thanks. I'm working on some code to perform the discovery constantly in the background to over come issues like this. This will be part of the helper integration work.

**Comment by gdachs** [comment]
That sounds good. I did this only because I need something now ;).

Btw. I still need this: https://github.com/hippojay/plugin.video.plexbmc/pull/109/commits
Doesn't work without this.

**Comment by gdachs** [comment]
Oh, prefetch the media data too, please. On slow devices it is pain to wait for the movie list to show up.

**Comment by gdachs** [comment]
currently the branch isengard-helper-merge is working without this patch.

**Pull request closed without merging**
