### PR TITLE
fix artwork and widget playback

### PR DESCRIPTION
**Pull request by marcelveldt**
This will properly assign the artwork for the listitems and will also enable proper playback from widgets when a dynamic content path is used.

Had some users for my skin who are actively using the plex integration and complained about these issues.

### CODE REVIEW

**Comment by hippojay** [comment]
Thanks. Let me check it out.   Is this for the Titan skin?  I'm looking to work slightly closer with a few skin developers on plexbmc integration to try and improve the gui components and make it a lot more seamless.

**Comment by marcelveldt** [comment]
Hi, this is not only for Titan skin. Any skin will benefit from it.

As for the integration options: I have already done that for you and now it is easy for any skin developer to have the plexbmc support without changes to their skin code.

I did this with my skinhelper project together with skin shortcuts.
https://github.com/marcelveldt/script.skin.helper.service

In the readme check the smart shortcuts section...

**Comment by hippojay** [comment]
Absolutely fantastic. I'll check it out in details.

**Comment by hippojay** [comment]
HI - I've merged these into my later isengard-fixes branch - which will be tested and moved into the isengard branch (which will become the new plexbmc release).  I've also put in some updates to make my code cleaner and also allow banners to be correctly formatted when using myplex (adding tokens and, for isengard, allowing https).  My commits are in this branch here for helix if you want to merge them across: https://github.com/hippojay/plugin.video.plexbmc/tree/pr/129

Thanks again for these.  

I've had some people contact me about creating skin updates for plexbmc (mostly in amber) , so I'm pointing them towards your skin.helper.service.

**Comment by marcelveldt** [comment]
Hi @hippojay were the artwork changes already pushed to your isengard branch ?
I still get some users complaining about the artwork being incorrectly assigned...

http://forum.kodi.tv/showthread.php?tid=251292&pid=2182491#pid2182491

**Comment by chadbaum** [comment]
Hi hippoyjay, I'm the titan user.  Been experimenting with titan as a shift from amber and I think Titan has all the right configuration options to make a lot of PlexBMC users happy if we can nail down a few last niggles.  I tried the isengard-fixes and isengard branch today with Titan and it wouldn't connect to my Plex, so I rolled back to beta4, and then marcel's modification of beta4 to get certain things working.  Let me know if you need me to test anything.

**Pull request closed without merging**
