### PR TITLE
Update plexbmc.py

### PR DESCRIPTION
**Pull request by randomevents**
Adds count to section.count variable, changes recent container size of media type

### CODE REVIEW

**Comment by hippojay** [comment]
You might have to explain this one to me :)  

Is this to only request as many items as the skin has slots for?  So if the skin can only show 5 recent items, then we only request 5, rather than 15?  Or does this only p[ull recently added from sections that are being displayed on the home menu (so don't grab from a section that we have hidden in Amber?)

My only concern is the use xbmc.getCondVisibility - I've had bad experiences of it causing slow downs.  We might end up penalising everyone for a small speed up for the ones who have hidden sections.

One thing I was going to look at it paralleling the gathering of this info - it might be worth spending the time spinning up some threads to do this, and this might get better performance for everyone.

**Comment by hippojay** [comment]
Also - i'm looking at moving some of this functionality to Plexbmc Helper, to run the discovery and skin setup, which means I can do more in the background.  plexbmc would then simple be the foregound task that displays lists and plays media.

**Comment by randomevents** [comment]
Morning, in hindsight the variable name should be something like skinID as opposed to count. I could also switch the test back to SkinHasSetting if that helps in your experience. The only reason I used xbmc.getCondVisibility was that I was trying to get it to work for a day not realizing I was misspelning 'hide.plexbmc.~' as 'hide.plexmbc.~' and was testing every method. I'd imagine that this is more useful to server admins then anyone else. Having this in the addon would be also useful as I'm following peckino's suggestion and working on a programmatic build of the skin so as not to be hampered by the a static xml file.

**Comment by randomevents** [comment]
Sorry I didn't address the first part of your message. Combined with variable added to section (.count) in plexserver.py, this change will only do PMS calls for visible libraries. There's also a change to pull more Recently Added Items for TV Shows, so that adding seasons of show wouldn't totally clear out the Recently Added bar (because the items would be grouped to seasons). Now that I think about it, it would be better to also add a sectionCurrentRecentCounter so that the items on the bar wouldn't be astronomically high if no complete seasons were added. A settings item for max Recent/Deck items could drive that variable and the non episode PMS pull (or just leave it at 15)

**Comment by hippojay** [comment]
Thanks. Moving to dynamic lists should help simplify the addon. Let me know if you need any help - I dare say that some tweaks will be needed to get it working fully.

**Comment by randomevents** [comment]
Will unify requests

**Pull request closed without merging**
