### PR TITLE
Fix fallback to local server on duplicate

### PR DESCRIPTION
**Pull request by pdegeus**
The fallback to the local address of a server also available on myPlex
failed. This fix makes sure the local address is used and also updates
the section retrieval to use the latest local (non-myPlex) REST API.

### CODE REVIEW

**Comment by hippojay** [comment]
Unfortunately, this produces duplicate sections where a local server is also present on myplex.  Because /system/library is used to get section listings, it doesn't matter if the server list is deduplicated, because the entire library is retrieved.

I have taken the global g_stream fix though, been meaning to fix it for ages, but other things keep popping up.

**Comment by pdegeus** [comment]
Does it? My server is also on myPlex and I'm seeing the sections only once; the server list is reduced to only the local address of the server, which returns its own section list without any duplicates. I changed the local URL removing the '/system' part, since that resulted in a 404. Is this a known change to the API with another fix then?

**Comment by hippojay** [comment]
Are you using it with an particular skin? I definitely saw duplicate section names.

The use of /system/library is part of the API, as it is how clients such as iOS work. Plus it reduces the number of http calls, rather than one per server.   What plex server platform/version are you using?

Also, what exactly was the issue you were fixing?

**Comment by pdegeus** [comment]
Ok let me give you some more details :)

I'm using XBMC Eden on ATV2 with your plugin, testing the latest snapshot of your Eden branch from GitHub. As skin I'm using the modified version of Confluence for PleXBMC found on the forums. My only server is the Linux PMS 0.9.6.3 running on my Synology NAS. The server is published to myPlex and available in my home network.

When I tested your latest changes, I noticed the section links of the skin used the remote address of the PMS found on myPlex, instead of the local address. This was caused by the call to '/system/library/sections', which returns a '404 Not Found' on my PMS. Removing the myPlex login and only setting a local server also failed: after fixing a problem with an uninitialized variable (aToken), no sections could be found because of the 404 on the URL.

I verified the URL by testing manually and found out '/library/sections' (without /system) does work and returns the server sections. The result however was different to the result the code was expecting, so I added code to handle the local response.

To easily filter out duplicates I also changed the input of getAllSections: instead of using g_serverdict it now receives a resolved/filtered list of servers from the skin() method, which in turn retrieves that list from resolveAllServers().

For my setup these changes work, but I may of course have broken other configurations. I also tested the changes with only a local server address configured in PleXBMC and with only myPlex configured. Both situations work.

**Comment by hippojay** [comment]
I've seen some messages on the plex forum about /system going missing on linux PMS.  I think this should be the first step, as /system/library/section is (or should be) a valid URL.

The use of /library/sections is how the older v1 plugin used to work, but it creates a number of extra calls to the web server, so slows things down slightly.

I'll check out the uninitalised token (aToken) as something should be returned from the authentication function, even if it's just a blank string..

Thanks

**Pull request closed without merging**
