### PR TITLE
"server-cache" breaking changes/testing + fixes

### PR DESCRIPTION
**Pull request by wezhunter**
Hi - your friendly github stalker here :)

I see your still working on server-cache branch but thought I would test and see if can fix some bugs.
Found three breaking changes so far. Attached are simple pull requests.

Hope it helps.

If you need any help with testing/dev don't hesitate to drop me a mail would love to help out.

PS: Nice to see your planning on the dict of dict and hopeful caching, I never got round to it to be honest.

Cheers,
Wez

### CODE REVIEW

**Comment by hippojay** [comment]
Thanks - i'll have a look through this.

This branch was put together to deal with a server discovery and addressing issue - the way I did it was no longer valid and was producing issues.  So i now do discovery over the network and talk to each media server.  It's slightly slower than before, but more robust.

When doing this, I tried to simplify the process and also rely less on settig global variables but pass servers lists about.  Combining the two has made it a little easier to follow the process - although it's still a little messy due to the way XBMC addons work (i.e. no persistent objects, else I would have created a media server class).

So, now that I pass lists about, I should be able to cache these and speed things up.  I did put in some test code and it seemed to work - but there is an issue with caching bad data.  I need a way of invalidating the cache so that I can implement a "refresh" when you don;t see the servers you expect.  Any ideas would be great!

Also - i can;t implement a sectin listing cache, because it would cache the resume time - and due to the changes I had to make to get skin watched flags working, this means that the resume would never update.

1 step forward, 2 steps back..

**Comment by wezhunter** [comment]
Yeah to me it seems the right way to go. Caching - I will see what I can do today with cache expiry. Might be a case of using the manual cache functions in common plugins cache and creating a timer class for expiration etc.

Section list caching is a definite no-go as I found out the hard way... :)

**Comment by hippojay** [comment]
I wrote a patch the other day to the cache plugin which put in a function cache delete.  Looking at how the implement the cache it seems like the only way to do it is in a separate function, without breaking the cache plugin interface.

Because the use a hash against the function name + arguments, it means you need all the info to remove that cache entry or delete everything in that cache.  I might submit it, but I do question whether that plugin has any active development.

So, your way may be better - it might make more sense to cache bits of information, rather than wholesale functions:
- Cache the local servers names
- Cache the myplex servers names
- Cache the available sections for each servers

I should already have these as separate items, so it would just be a case of adding the cache code against these dicts/lists.  Then a refresh can simply delete the cache and rerun the items again.

It might also be possible to cache some of the intermediate menus.

**Comment by wezhunter** [comment]
I've seen your post on XBMC forums. I too looked into this while I was testing caching. 
Below is where the plugin repo is stored and hosted by the XBMC team (if it helps).
http://xbmc.git.sourceforge.net/git/gitweb.cgi?p=xbmc/scripts;a=tree;f=script.common.plugin.cache;h=43bea3ef4797be9410677e080fa06312274a8b21;hb=refs/heads/frodo

Maybe its worth contacting TobiasTheCommie who calls himself "TheCollective" on the forum post? From what it appears though - doesn't look very active! 
Failing that maybe Martijn Kaijser on XBMC team could split of the repo or publish your updated version, obviously breaking changes would be am major issue. You just don't want to become the maintainer of another damn plugin though - I bet its a pain in the ass :-)

Failing all that I can only really think of two alternatives - 
Rip and integrate an updated caching StorageServer itself into plexbmc plugin, probably the most time costly. Settings, resources etc all need their refs updating/changing accordingly. Its a python script at the end of the day.

Write a custom class within plexbmc that implements the standard StorageServer via individual getMulti and setMulti using a generated hash. Pretty much writing an equivalent Function based caching method with expiration.

Didn't get much chance to look into all of them in any detail today but should have time tomorrow (or today whichever comes first!)

**Comment by hippojay** [comment]
Would be interesting to see if this worked ok - just been testing to see whether the plugin cache can store pickle objects - which it can (as long as they are base64 encoded).  So it might be an option to create some plex server classes for server and sections - would make tracking them and managing a bit easier I think.

**Comment by hippojay** [comment]
basic cache added now = so closing this pull

**Pull request closed without merging**
